services:
  mongodb-container:
   image: ecommerce-mongodb:latest
   build: 
     context: ./mongodb
     dockerfile: Dockerfile
   ports:
    - "27017:27017"
   networks:
    - orders-mongodb-network

  mysql-container:
   image: ecommerce-mysql:latest
   build: 
     context: ./mysql
     dockerfile: Dockerfile
   environment:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
   ports:
    - "3306:3306"
   networks:
    - products-mysql-network

  postgres-container:
   image: ecommerce-postgres:latest
   build: 
     context: ./postgres
     dockerfile: Dockerfile
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P@ssw0rd
    - POSTGRES_DB=eCommerceUsers
   ports:
    - "5432:5432"
   networks:
    - users-postgres-network

  redis:
   image: redis:latest
   ports:
    - "6379:6379"
   networks:
    - ecommerce-network

  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
     - ecommerce-network

  apigateway:
    image: apigateway:latest
    build:
      context: ./OrdersService
      dockerfile: APIGateway/Dockerfile
    ports:
     - "4500:8080"
    networks:
     - ecommerce-network
    depends_on:
     - orders-microservice
     - products-microservice
     - users-microservice

  users-microservice:
   image: users-microservice:latest
   build: 
    context: ./UsersService
    dockerfile: eCommerce.API/Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - POSTGRES_HOST=postgres-container
    - POSTGRES_PORT=5432
    - POSTGRES_DATABASE=eCommerceUsers
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P@ssw0rd
    - RabbitMQ_HostName=rabbitmq
    - RabbitMQ_Port=5672
    - RabbitMQ_UserName=guest
    - RabbitMQ_Password=guest
    - RabbitMQ_Users_Exchange=users.exchange
   networks:
    - users-postgres-network
    - ecommerce-network
   depends_on: 
    - postgres-container

  products-microservice:
   image: products-microservice:latest
   build: 
    context: ./ProductsMicroservice
    dockerfile: ProductsMicroservice/Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - MYSQL_HOST=mysql-container
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=ecommerceproductsdatabase
    - MYSQL_USER=root
    - MYSQL_PASSWORD=P@ssw0rd
    - RabbitMQ_HostName=rabbitmq
    - RabbitMQ_Port=5672
    - RabbitMQ_UserName=guest
    - RabbitMQ_Password=guest
    - RabbitMQ_Products_Exchange=products.exchange
   networks:
    - products-mysql-network
    - ecommerce-network
   depends_on: 
    - mysql-container

  orders-microservice:
    image: orders-microservice:latest
    build: 
     context: ./OrdersService
     dockerfile: OrdersMicroserviceAPI/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - MONGODB_HOST=mongodb-container
     - MONGODB_PORT=27017
     - MONGODB_DATABASE=OrdersDatabase
     - UserMicroservicePort=8080
     - UserMicroserviceName=apigateway
     - ProductMicroservicePort=8080
     - ProductMicroServiceName=apigateway
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - RabbitMQ_HostName=rabbitmq
     - RabbitMQ_Port=5672
     - RabbitMQ_UserName=guest
     - RabbitMQ_Password=guest
     - RabbitMQ_Products_Exchange=products.exchange
     - RabbitMQ_Users_Exchange=users.exchange
    networks:
     - orders-mongodb-network
     - ecommerce-network
    depends_on: 
     - mongodb-container
     - rabbitmq
     - redis


networks:
 ecommerce-network:
  driver: bridge
 users-postgres-network:
  driver: bridge
 products-mysql-network:
  driver: bridge
 orders-mongodb-network:
  driver: bridge